version: "3"

networks:
  task-manager:

volumes:
  app_data: {}

services:

  node:
    build: ./backend
    depends_on:
      - postgres
    volumes:
        - ./backend/src:/home/node/app/src
        - ./backend/tsconfig.json:/home/node/app/tsconfig.json
    ports:
      - 8080:4200
    networks:
      - task-manager

  postgres:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - ./postgres/:/etc/postgres/
    ports:
      - 5432:5432
    networks:
      - task-manager

  app:
    build: ./frontend
    volumes:
      - app_data:/var/log
    ports:
      - 8081:80
    networks:
      - task-manager
