services:
  node:
    build: ./src
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
    ports:
      - 8000:4200
    volumes:
      - ./src:/home/node/app/src
      - ./tsconfig.json:/home/node/app/tsconfig.json
  postgres:
    container_name: postgres_nest
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_HOST=${DATABASE_HOST}
    volumes:
      - postgres-data:/data
    ports:
      - 5532:${DATABASE_PORT}
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_LISTEN_PORT=80
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 80:80
    networks:
      - postgres
    restart: unless-stopped
    tty: true

networks:
  postgres:
    driver: bridge
volumes:
   postgres-data:
   pgadmin: