version: "3"

services:
  node:
    build: ./backend
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
    volumes:
      - ./backend/src:/home/node/app/src
      - ./backend/tsconfig.json:/home/node/app/tsconfig.json
    ports:
      - 8080:4200
    restart: unless-stopped

  postgres:
    container_name: postgres_nest
    image: postgres
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_HOST=${DATABASE_HOST}
    volumes:
      - pg-dataset:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    restart: unless-stopped

  app:
    build: ./frontend
    depends_on:
      - node
    ports:
      - 80:80
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/public:/usr/share/nginx/html
    restart: unless-stopped
volumes:
  compose-lesson:
  pg-dataset: